spec:                                                                                    
  replicas: 2                                                                            
  template:                                                                              
    spec:                                                                                
      containers:                                                                        
        - env:                                                                           
            - name: METRICS_CONTEXT_CLASSPATH                                            
              value: /metrics/resources/                                                 
            - name: KAFKA_BOOTSTRAP_SERVERS                                              
              value: 'my-kafka-cluster-kafka-bootstrap.amq.svc.cluster.local:9092'       
            - name: KAFKA_CONSUMER_TOPIC                                                 
              value: metrics-data                                                        
            - name: KAFKA_PRODUCER_TOPIC                                                 
              value: metrics-data                                                        
            - name: METRICS_DATASOURCE_DIALECT_CLASS                                     
              value: org.hibernate.dialect.H2Dialect                                     
            - name: METRICS_DATASOURCE_DRIVER                                            
              value: org.h2.Driver                                                       
            - name: METRICS_DATASOURCE_PASSWORD                                          
              value: password                                                            
            - name: METRICS_DATASOURCE_URL                                               
              value: 'jdbc:h2:mem:testdb'                                                
            - name: METRICS_DATASOURCE_USERNAME                                          
              value: sa                                                                  