- name: metric-app-h2 
  generator:
    includes:
      - spring-boot
    config:
      spring-boot:
        color: always
  enricher:
    includes:
      - jkube-openshift-service-expose
      - jkube-openshift-route
    excludes:
      - jkube-expose
- name: metric-app-postgres 
  generator:
    includes:
      - spring-boot
    config:
      spring-boot:
        color: always
  enricher:
    includes:
      - jkube-openshift-service-expose
      - jkube-openshift-route
    excludes:
      - jkube-expose
- name: metric-app-mariadb 
  generator:
    includes:
      - spring-boot
    config:
      spring-boot:
        color: always
  enricher:
    includes:
      - jkube-openshift-service-expose
      - jkube-openshift-route
    excludes:
      - jkube-expose